version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: python setup.py ldist
workflows:
  version: 2
  build-develop:
    jobs:
      - build:
        filters:
          branches:
            only: develop
